# .rubocop.yml
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 160


Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 9

RSpec/NestedGroups:
  Max: 4
