mutation LineItemUpdates($inputs: [LineItemUpdateInput!]!) {
  lineItemUpdates(inputs: $inputs) {
    id
    category { id name }
    color
    description
    itemNumber
    items
    markupPercentage
    merch
    personalizations { id name personalization }
    poLineItem { id description itemNumber items position sizes { count size } }
    position
    price
    priceReceipt { defaultMarkupPercentage description price signature }
    product { id brand color description itemNumber }
    productStatus
    sizes { count size }
    taxed
  }
}
